### ISSUE TITLE
Could the install script check for needed opengl extensions ?

### ISSUE THREAD

**Issue by ghost** [magic-lang/magic-tools#10]
Yesterday I needed to setup a fresh linux system with dev tools. Using the `install-magic-tools` worked perfectly, but I needed to download some opengl packages manually:

```
sudo apt-get install mesa-common mesa-utils-extra libglew-dev libegl1-mesa-dev libgles1-mesa-dev libgles2-mesa-dev
```

(I think this is all, I will double check at home)

could the install script do that for me ?
Or maybe a separate script / entry in readme to completely setup the dev environment (even with `build-essential` etc)?
@thomasfanell @marcusnaslund

**Comment by marcusnaslund** [comment]
Yes, I would like that too.

**Comment by thomasfanell** [comment]
@sebastianbaginski funny you should mention that, I did the exact same thing yesterday evening, and I also thought about it... wow.

**Comment by ghost** [comment]
I guess it means we're nerds :D

**Comment by marcusnaslund** [comment]
Great minds think alike.

**Comment by thomasfanell** [comment]
Fixed.

**Comment by ghost** [comment]
Nice.
